version: '3.8'

services:
  db:
    image: postgres:15
    container_name: motorcycle_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: motorcycle_shop
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    networks:
      - motorcycle_network

networks:
  motorcycle_network:
    driver: bridge

volumes:
  pgdata: