version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "4200:4200"
    environment:
      - DATABASE_URL=postgresql://admin:admin123@db:5432/motorcycle_shop
    depends_on:
      - db
    networks:
      - motorcycle_network

  db:
    image: postgres:15
    container_name: motorcycle_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: motorcycle_shop
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    networks:
      - motorcycle_network

networks:
  motorcycle_network:
    driver: bridge

volumes:
  pgdata: